### ISSUE TITLE
Crashes upon entering Video Settings menu with Sodium installed

### ISSUE THREAD

**Issue by Auscobe** [uku3lig/fractionalgui#5]
[crash-2023-11-30_14.25.26-client.txt](https://github.com/uku3lig/fractionalgui/files/13517472/crash-2023-11-30_14.25.26-client.txt)
[latest.log](https://github.com/uku3lig/fractionalgui/files/13517474/latest.log)

Submitting both my latest.log and crashlog cause I don't know for sure which one to upload. Using the version on Modrinth that's compatible with 1.20.1, running Quilt. I know you can get that from the logs, just sharing out of habit =P

There is another mod that does this, so I'm just pointing this out in case you care (I don't blame you if you don't since you only made it out of boredom). Would be good to at least provide a warning about the incompatibility if not a fix or whatever you will. https://modrinth.com/mod/advanced-ui-scale/

**Comment by uku3lig** [comment]
:cdisaster:

thanks for the report, i'll see if i can reproduce and what i can do

**Comment by uku3lig** [comment]
fixed in [1.0.4+mc1.20.1](https://modrinth.com/mod/fractionalgui/version/1.0.4+mc1.20.1), thanks for the report!
